# Generated by Django 2.2.1 on 2019-09-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('preco', models.FloatField(max_length=5, verbose_name='Preco')),
                ('quantidade', models.CharField(max_length=200, verbose_name='Quantidade')),
                ('descrição', models.TextField(max_length=3000, verbose_name='Descrição')),
                ('foto', models.ImageField(null=True, upload_to='cursos', verbose_name='Foto')),
            ],
        ),
    ]
