# Generated by Django 2.2.2 on 2019-09-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adicionais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('preco', models.FloatField(max_length=5, verbose_name='Preco')),
                ('foto', models.ImageField(null=True, upload_to='adicional', verbose_name='Foto')),
            ],
        ),
        migrations.CreateModel(
            name='Coberturas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('foto', models.ImageField(null=True, upload_to='cobertura', verbose_name='Foto')),
            ],
        ),
        migrations.CreateModel(
            name='Cremes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('foto', models.ImageField(null=True, upload_to='creme', verbose_name='Foto')),
            ],
        ),
        migrations.CreateModel(
            name='Recheios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('foto', models.ImageField(null=True, upload_to='recheio', verbose_name='Foto')),
            ],
        ),
    ]
