# Generated by Django 2.2.2 on 2019-09-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_adicionais_coberturas_cremes_recheios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapio',
            name='foto',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Foto'),
        ),
    ]
